# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f71a03b59007c9544257ef4f3d2e9d1c3f007a5e975f6a7d0d93951a232bd40f63a38462f2b128460e199f3c2cc293456b9cc4ce186b7d2f9400fab01d2cc5e9

test:
  secret_key_base: 049440e881e7bdd8b69d92472cbd34f6c14c2db4038f30f6faccc62ce501748cc23a7d81a76c8bfb0d0ad5281d18b9c8d77c8f05c23346005781a4f6bea8c2ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
